// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// // export default function RootLayout({ children }) {
// //   return (
// //     <html
// //       lang="en"
// //       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
// //     >
// //       <body className="min-h-full flex flex-col">{children}</body>
// //     </html>
// //   );
// // }

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en" suppressHydrationWarning>
//       <body>{children}</body>
//     </html>
//   );
// }

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import { Toaster } from "react-hot-toast";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "MarketMind",
  description: "Stock Analysis Platform",
};

// export default function RootLayout({ children }) {
//   return (
//     <html
//       lang="en"
//       suppressHydrationWarning
//       className={`${geistSans.variable} ${geistMono.variable}`}
//     >
//       <body>{children}</body>
//     </html>
//   );
// }

export default function RootLayout({ children }) {
  return (
    
    <html lang="en">
      <body>
        <Providers>
          <Toaster
  position="top-center"
  toastOptions={{
    style: {
      background: "#020617",
      color: "#fff",
      border: "1px solid rgba(255,255,255,0.1)",
    },
  }}
/>
          {children}
        </Providers>
      </body>
    </html>
  );
}
